[build]
  base = "client"
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.20.6"
  NPM_FLAGS = "--no-audit --no-fund"
  VITE_API_URL = "https://projectsoulsync.onrender.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.images]
  compress = true
