services:
  - type: web
    name: soulsync-backend
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: NODE_ENV=production npm start
    nodeVersion: 18.20.6
    buildFilter:
      paths:
        - server/**
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        value: 8f9a12b3c4d5e6f7g8h9i0j1k2l3m4n5o6p7q8r9s0t1u2v3w4x5y6z7a8b9c0
      - key: DATABASE_URL
        value: postgresql://journal_app_db_c496_user:CGBh2pZUfWIZuku5abLeiI18tVDrTxeO@dpg-cu4rmq5ds78s73ds0nm0-a.oregon-postgres.render.com/journal_app_db_c496
      - key: CORS_ALLOWED_ORIGINS
        value: https://soulsync.netlify.app,https://679e6bf092f0a8dc3d5ee08b--soulsync.netlify.app,http://localhost:3000,http://localhost:5173
      - key: FRONTEND_URL
        value: https://soulsync.netlify.app/
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
