services:
  - type: web
    name: soulsync-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: CORS_ORIGIN
        value: https://soulsync.netlify.app
